### ISSUE TITLE
Table dash length indicators can cause weird behavior

### ISSUE THREAD

**Issue by cmrschwarz** [henriklovhaug/md-tui#105]
## Issue
Observed behavior:
- Repro1: When the dashed lines are shorter than the table header, the table breaks completely.
- Repro2: When the dashed table header lines are shorter than the number of characters, the cell is truncated. 
- Repro3: Table is larger than expected, presumably in an attempt to pad for characters that aren't being displayed.

Expected behavior:
- Repro 1: Table doesn't break, size is increased to fit content.
- Repro 2: Table size is increased or content is wrapped
- Repro 3: Table is not bigger than neccessary

## Reproduction

```
| Repro1 | Table | 
| ----   | ----- |
| a      | b     | 

---

| Repro2 | Table |
| ------ | ----- |
| 0123456789-0123456789 | b |

---

| Repro3     | Table | 
| ---------- | ----- |
| ```xyz```  |     b | 

```

## Current MDT Output

<pre>
  Repro                                                                        
  Table
  ----
  a
  b

  —————————————————————————————————————————————————————————————————————————————

  Repro2     Table                                                             
  0123456789 b

  —————————————————————————————————————————————————————————————————————————————

  Repro3         Table                                                         
  ``xyz``        b
</pre>

## Github Output for Reference

| Repro1 | Table | 
| ----  | ----- |
| a     |     b | 

---

| Repro2| Table |
| ------ | ----- |
| 0123456789-0123456789 | b |

---

| Repro3     | Table | 
| ---------- | ----- |
| ```xyz```  |     b |

**Comment by henriklovhaug** [comment]
It's now mostly fixed in #121, but table cell word wrapping is still not implemented. I have not decided what behaviour to expect there yet
