### ISSUE TITLE
md-tui as widget to be intergrated in other TUI projects

### ISSUE THREAD

**Issue by pythops** [henriklovhaug/md-tui#111]

**Comment by henriklovhaug** [comment]
So, what to do with this issue? Authors of other TUIs are welcome to have a chat on how to integrate `MD-TUI` into other programs.

**Comment by henriklovhaug** [comment]
Let me know if anyone wants to integrate this app

**Comment by pythops** [comment]
I want to, I have created [agadir](https://github.com/pythops/agadir) to be able to serve blog posts over TUI and I will need to build something similar for a better user experience. so I can integrate with md-tui that would save me a lot of time and energy :pray:

**Comment by pythops** [comment]
I am wondering on creating a widget for markdown rendering, same logic as [tui-textarea](https://github.com/rhysd/tui-textarea) for example is the widget to use for text input. That way it will be easier for other TUI to integrate with it
let me know if the idea makes sense to you. I am willing to help ofc in case you wanna proceed this way

**Comment by henriklovhaug** [comment]
I could make it work as library as well. It would not be ergonomic to then ship your own key binds from your application to the pop up area, but if you're only looking for the rendering, it should be fine.

**Comment by pythops** [comment]
yeah I only want the rendering part with the scroll and the image sizing
