### ISSUE TITLE
Default keybinding are terrible

### ISSUE THREAD

**Issue by tommythorn** [henriklovhaug/md-tui#112]
I saw a toot about this and jumped to install it, but it seemed to only display the first screen full.  I expected it to work like less, but neither space, -, arrow-up/down, nor return did anything.  I tried running `mdt --help` for a manual but it said it couldn't find `--help`.

I finally went to track down the home page for this and found it uses the arcane VI conventions.  Well that was not definitely not obvious and frankly unpleasant.

**Comment by tommythorn** [comment]
You asked for issues and I reported my experience.  It looks interesting and it was definitely something that is needed.  I didn’t see the help, but it could be related to the colors which made part of it unreadable (which could be the fault of my terminal settings, so I didn’t mention it).

I disagree with your expected defaults, less binding are obviously what I would expect for a terminal viewer.

**Comment by henriklovhaug** [comment]
Change the key binds however you see fit. https://github.com/henriklovhaug/md-tui/releases/tag/v0.8.0
