### ISSUE TITLE
Center Interface

### ISSUE THREAD

**Issue by DarkKronicle** [henriklovhaug/md-tui#132]
Hello, I was wondering if it was possible to add a feature to center the preview if the width of the terminal is big enough.

One way this could work:

- Have a config option that specifies justification. `justification = <center, left, right>`
- Have a config option to specify width, `max_width = 50`

**Comment by henriklovhaug** [comment]
Yeah I could add that. Width already exists, so we don't need another one.

**Comment by henriklovhaug** [comment]
It's now in main. Gonna try to solve a few more issues before a new release
