### ISSUE TITLE
Weird rendering with windows style CRLF

### ISSUE THREAD

**Issue by jkrshnmenon** [henriklovhaug/md-tui#139]
When trying to open a file that contains the windows style CRLF endings, the rendering looks weird.
I can confirm that replacing the \x0d\x0a with \x0a does fix the rendering. 
But I'm not sure if this is a case you'd want to handle within mdt.

Screenshot of the problem is attached.

![Screenshot from 2024-07-25 13-53-20](https://github.com/user-attachments/assets/46ac4d72-809a-4cf7-9610-12e3f2085709)

**Comment by jkrshnmenon** [comment]
Oops, forgot to upload the actual MD file.

[foo.md](https://github.com/user-attachments/files/16383701/foo.md)

**Comment by henriklovhaug** [comment]
I have gotten the same bug on *nix system with another file. It wasn't a problem earlier, so I have to do a bisect to find the culprit.
