### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by maxigaz** [henriklovhaug/md-tui#140]
I've been using `glow` as a markdown previewer inside `vifm`. I've just discovered `md-tui`, and I really like it so far.

To my knowledge, vifm can only use a tool as a previewer if it outputs something straight to stdout, and then, vifm acts like a pager, so the output can be scrolled up and down, just like in `less`. I'm not entirely sure how `glow` works, but I think it detects whether it was called through a pipe or not, and based on that, opens a file in either interactive and non-interactive mode.

Could `md-tui` also have the option to output rendered straight to stdout?

Also, thank you for the software!

**Comment by henriklovhaug** [comment]
The render workflow of `md-tui` is really tied to [ratatui](https://ratatui.rs). It's the library which handles the colouring during rendering and uses the terminal in alternate mode. To use this program without the keyboard handling, link functionality, or search, it's just a formatter basically. At that point, in my opinion, `glow` does a better job. 

Pipe detection is not hard to achieve, but it would loose all colouring without a major rewrite.

**Comment by maxigaz** [comment]
The main reason I considered `md-tui` as a viable alternative is because it performs much better based on my (limited) testing. For instance, I have a markdown file that is around 700 kB in size. While it takes `glow` more than 10 seconds to open it (in both modes), `md-tui` opens it _instantly_.

But I understand if this is a 'wontfix'.

**Comment by henriklovhaug** [comment]
The parsing is a lot faster as long you don't have images it needs to fetch over the internet than `Glow`.  Maybe [mdcat](https://github.com/swsnr/mdcat) is a good alternative
