### ISSUE TITLE
Feature Request: Add support for luau syntax highlighting

### ISSUE THREAD

**Issue by 0xJWLabs** [henriklovhaug/md-tui#143]
Since there is a tree-sitter of luau now, can you add support for luau language since it kinda has different syntax highlight to lua? Thanks!

Here is the link to the tree sitter
https://github.com/tree-sitter-grammars/tree-sitter-luau

**Comment by henriklovhaug** [comment]
The crate they are supplying, or someone else is building for them, is too old to work with `md-tui`. I would have to downgrade all other parsers. [Link to luau crate](https://crates.io/crates/tree-sitter-luau)

**Comment by 0xJWLabs** [comment]
@henriklovhaug Did you mean like their github's repo is different than their crate yes?

**Comment by henriklovhaug** [comment]
I use rust bindings I find on crates.io along with tree-sitter itself. Their API is breaking between versions, so the luau one I found is for tree-sitter 0.20 and all the other I use is for 0.21. They are not compatible. I may package both version of tree-sitter with `md-tui`, but I see that as a last resort.

**Comment by 0xJWLabs** [comment]
Mind to add with my fork one? @henriklovhaug since the maintainer of that luau grammar isn't really active.

https://crates.io/crates/tree-sitter-luau-fork, I set tree-siter to ^0.21.0

**Comment by henriklovhaug** [comment]
I tried adding it, but it won't build. You can see it on the linked branch.

**Comment by 0xJWLabs** [comment]
Can you try update it to 0.1.3, I try yours using cargo run, and it works @henriklovhaug
