### ISSUE TITLE
Code blocks with triple tilde are interpreted as strikethrough

### ISSUE THREAD

**Issue by jkrshnmenon** [henriklovhaug/md-tui#145]
There's a couple of issues that MDT runs into when rendering this particular file : [UAFBench](https://github.com/strongcourage/uafbench/blob/master/README.md)

The code blocks that use the triple tilde (~~~) are interpreted as strikethrough.
There's also some weird characters in the output.

![image](https://github.com/user-attachments/assets/faaceed8-3ee3-447e-ae7c-c6e278c11f7b)

**Comment by henriklovhaug** [comment]
I haven't added triple strikethrough as code block definition. Will fix
