### ISSUE TITLE
Latest version  runs with an error under win11 WSL

### ISSUE THREAD

**Issue by zhoushun123** [henriklovhaug/md-tui#155]
md-tui-x86_64-unknown-linux-gnu
v0.8.5 & 0.8.6 
X64 win 11 23H2  22631.4112，WSL1
Error message：Error: Os { code: 25, kind: Uncategorized, message: "Inappropriate ioctl for device" }

v0.8.4 and before works fine

**Comment by henriklovhaug** [comment]
Does it fail if you compile it yourself with cargo?

**Comment by henriklovhaug** [comment]
No followup provided
