### ISSUE TITLE
Link colors

### ISSUE THREAD

**Issue by donovanglover** [henriklovhaug/md-tui#156]
Currently link colors work when URLs are in the format `[Example](https://example.com)`

Would be great if links like `<https://example.com>` or even `https://example.com` had colors as well similar to [glow](https://github.com/charmbracelet/glow).

**Comment by orhun** [comment]
Sounds like a straightforward feature to implement, would you be interested in contributing? 🐻

**Comment by henriklovhaug** [comment]
It would be preferable to catch URL as early as possible. I think defining the pattern in the pest file would be the option

**Comment by orhun** [comment]
I tried out some stuff: #157

But unfortunately I couldn't get it working. It is either not being parsed at all or being parsed as a LinkData.

I appreciate any guidance towards finishing the implementation!

**Comment by henriklovhaug** [comment]
Added comment for help in PR
