### ISSUE TITLE
Support Wiki-Syntax

### ISSUE THREAD

**Issue by Fildor** [henriklovhaug/md-tui#75]
Feature suggestion:

Support Wiki-Style links like

```
[[https://external.lnk]]

[[linkToLocalFile]]

[[#internalLink]]
```

See also: https://pandoc.org/MANUAL.html#extension-wikilinks_title_after_pipe

**Comment by henriklovhaug** [comment]
I agree. Still several things of the specification that is not supported yet

**Comment by Fildor** [comment]
You labeled it "bug". That seems harsh. AFAIK Wiki-Links are not a "basic" spec feature.
I just thought it would be a cool enhancement (because I happen to use markdown for my personal wiki).

Best wishes, Fil

**Comment by henriklovhaug** [comment]
Going to support

```bash
[[linkToFile]]
[[URL|Some alternative text]]
```

This means 

```bash
[[Title|URL]]
```

Will not work
